// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "messages.g.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray<id> *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static id GetNullableObjectAtIndex(NSArray<id> *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface PGNDeviceInfoRequest ()
+ (PGNDeviceInfoRequest *)fromList:(NSArray<id> *)list;
+ (nullable PGNDeviceInfoRequest *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface PGNDeviceInfoReply ()
+ (PGNDeviceInfoReply *)fromList:(NSArray<id> *)list;
+ (nullable PGNDeviceInfoReply *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface PGNCounterRequest ()
+ (PGNCounterRequest *)fromList:(NSArray<id> *)list;
+ (nullable PGNCounterRequest *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface PGNCounterReply ()
+ (PGNCounterReply *)fromList:(NSArray<id> *)list;
+ (nullable PGNCounterReply *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@implementation PGNDeviceInfoRequest
+ (instancetype)makeWithPrefix:(nullable NSString *)prefix {
  PGNDeviceInfoRequest* pigeonResult = [[PGNDeviceInfoRequest alloc] init];
  pigeonResult.prefix = prefix;
  return pigeonResult;
}
+ (PGNDeviceInfoRequest *)fromList:(NSArray<id> *)list {
  PGNDeviceInfoRequest *pigeonResult = [[PGNDeviceInfoRequest alloc] init];
  pigeonResult.prefix = GetNullableObjectAtIndex(list, 0);
  return pigeonResult;
}
+ (nullable PGNDeviceInfoRequest *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [PGNDeviceInfoRequest fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.prefix ?: [NSNull null],
  ];
}
@end

@implementation PGNDeviceInfoReply
+ (instancetype)makeWithPlatform:(nullable NSString *)platform
    osVersion:(nullable NSString *)osVersion
    model:(nullable NSString *)model
    message:(nullable NSString *)message {
  PGNDeviceInfoReply* pigeonResult = [[PGNDeviceInfoReply alloc] init];
  pigeonResult.platform = platform;
  pigeonResult.osVersion = osVersion;
  pigeonResult.model = model;
  pigeonResult.message = message;
  return pigeonResult;
}
+ (PGNDeviceInfoReply *)fromList:(NSArray<id> *)list {
  PGNDeviceInfoReply *pigeonResult = [[PGNDeviceInfoReply alloc] init];
  pigeonResult.platform = GetNullableObjectAtIndex(list, 0);
  pigeonResult.osVersion = GetNullableObjectAtIndex(list, 1);
  pigeonResult.model = GetNullableObjectAtIndex(list, 2);
  pigeonResult.message = GetNullableObjectAtIndex(list, 3);
  return pigeonResult;
}
+ (nullable PGNDeviceInfoReply *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [PGNDeviceInfoReply fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.platform ?: [NSNull null],
    self.osVersion ?: [NSNull null],
    self.model ?: [NSNull null],
    self.message ?: [NSNull null],
  ];
}
@end

@implementation PGNCounterRequest
+ (instancetype)makeWithValue:(nullable NSNumber *)value {
  PGNCounterRequest* pigeonResult = [[PGNCounterRequest alloc] init];
  pigeonResult.value = value;
  return pigeonResult;
}
+ (PGNCounterRequest *)fromList:(NSArray<id> *)list {
  PGNCounterRequest *pigeonResult = [[PGNCounterRequest alloc] init];
  pigeonResult.value = GetNullableObjectAtIndex(list, 0);
  return pigeonResult;
}
+ (nullable PGNCounterRequest *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [PGNCounterRequest fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.value ?: [NSNull null],
  ];
}
@end

@implementation PGNCounterReply
+ (instancetype)makeWithValue:(nullable NSNumber *)value
    message:(nullable NSString *)message {
  PGNCounterReply* pigeonResult = [[PGNCounterReply alloc] init];
  pigeonResult.value = value;
  pigeonResult.message = message;
  return pigeonResult;
}
+ (PGNCounterReply *)fromList:(NSArray<id> *)list {
  PGNCounterReply *pigeonResult = [[PGNCounterReply alloc] init];
  pigeonResult.value = GetNullableObjectAtIndex(list, 0);
  pigeonResult.message = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable PGNCounterReply *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [PGNCounterReply fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.value ?: [NSNull null],
    self.message ?: [NSNull null],
  ];
}
@end

@interface PGNMessagesPigeonCodecReader : FlutterStandardReader
@end
@implementation PGNMessagesPigeonCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 129: 
      return [PGNDeviceInfoRequest fromList:[self readValue]];
    case 130: 
      return [PGNDeviceInfoReply fromList:[self readValue]];
    case 131: 
      return [PGNCounterRequest fromList:[self readValue]];
    case 132: 
      return [PGNCounterReply fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface PGNMessagesPigeonCodecWriter : FlutterStandardWriter
@end
@implementation PGNMessagesPigeonCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[PGNDeviceInfoRequest class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[PGNDeviceInfoReply class]]) {
    [self writeByte:130];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[PGNCounterRequest class]]) {
    [self writeByte:131];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[PGNCounterReply class]]) {
    [self writeByte:132];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface PGNMessagesPigeonCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation PGNMessagesPigeonCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[PGNMessagesPigeonCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[PGNMessagesPigeonCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *PGNGetMessagesCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    PGNMessagesPigeonCodecReaderWriter *readerWriter = [[PGNMessagesPigeonCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}
void SetUpPGNNativeDemoApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PGNNativeDemoApi> *api) {
  SetUpPGNNativeDemoApiWithSuffix(binaryMessenger, api, @"");
}

void SetUpPGNNativeDemoApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PGNNativeDemoApi> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.pigeon_demo_plugin.NativeDemoApi.getDeviceInfo", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:PGNGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getDeviceInfoRequest:error:)], @"PGNNativeDemoApi api (%@) doesn't respond to @selector(getDeviceInfoRequest:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        PGNDeviceInfoRequest *arg_request = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        PGNDeviceInfoReply *output = [api getDeviceInfoRequest:arg_request error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.pigeon_demo_plugin.NativeDemoApi.increment", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:PGNGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(incrementRequest:error:)], @"PGNNativeDemoApi api (%@) doesn't respond to @selector(incrementRequest:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        PGNCounterRequest *arg_request = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        PGNCounterReply *output = [api incrementRequest:arg_request error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
