// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class PGNDeviceInfoRequest;
@class PGNDeviceInfoReply;
@class PGNCounterRequest;
@class PGNCounterReply;

/// Request object for asking the host platform to describe itself.
@interface PGNDeviceInfoRequest : NSObject
+ (instancetype)makeWithPrefix:(nullable NSString *)prefix;
@property(nonatomic, copy, nullable) NSString * prefix;
@end

/// Reply object returned by the host platform.
@interface PGNDeviceInfoReply : NSObject
+ (instancetype)makeWithPlatform:(nullable NSString *)platform
    osVersion:(nullable NSString *)osVersion
    model:(nullable NSString *)model
    message:(nullable NSString *)message;
@property(nonatomic, copy, nullable) NSString * platform;
@property(nonatomic, copy, nullable) NSString * osVersion;
@property(nonatomic, copy, nullable) NSString * model;
@property(nonatomic, copy, nullable) NSString * message;
@end

/// Request object for a tiny native calculation.
@interface PGNCounterRequest : NSObject
+ (instancetype)makeWithValue:(nullable NSNumber *)value;
@property(nonatomic, strong, nullable) NSNumber * value;
@end

/// Reply object for the native calculation.
@interface PGNCounterReply : NSObject
+ (instancetype)makeWithValue:(nullable NSNumber *)value
    message:(nullable NSString *)message;
@property(nonatomic, strong, nullable) NSNumber * value;
@property(nonatomic, copy, nullable) NSString * message;
@end

/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *PGNGetMessagesCodec(void);

@protocol PGNNativeDemoApi
/// @return `nil` only when `error != nil`.
- (nullable PGNDeviceInfoReply *)getDeviceInfoRequest:(PGNDeviceInfoRequest *)request error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable PGNCounterReply *)incrementRequest:(PGNCounterRequest *)request error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpPGNNativeDemoApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PGNNativeDemoApi> *_Nullable api);

extern void SetUpPGNNativeDemoApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PGNNativeDemoApi> *_Nullable api, NSString *messageChannelSuffix);

NS_ASSUME_NONNULL_END
