// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.example.pigeon_demo_plugin

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is PigeonDemoFlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class PigeonDemoFlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Request object for asking the host platform to describe itself.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DeviceInfoRequest (
  val prefix: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DeviceInfoRequest {
      val prefix = pigeonVar_list[0] as String?
      return DeviceInfoRequest(prefix)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      prefix,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is DeviceInfoRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Reply object returned by the host platform.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DeviceInfoReply (
  val platform: String? = null,
  val osVersion: String? = null,
  val model: String? = null,
  val message: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DeviceInfoReply {
      val platform = pigeonVar_list[0] as String?
      val osVersion = pigeonVar_list[1] as String?
      val model = pigeonVar_list[2] as String?
      val message = pigeonVar_list[3] as String?
      return DeviceInfoReply(platform, osVersion, model, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      platform,
      osVersion,
      model,
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is DeviceInfoReply) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Request object for a tiny native calculation.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CounterRequest (
  val value: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CounterRequest {
      val value = pigeonVar_list[0] as Long?
      return CounterRequest(value)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      value,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is CounterRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Reply object for the native calculation.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CounterReply (
  val value: Long? = null,
  val message: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CounterReply {
      val value = pigeonVar_list[0] as Long?
      val message = pigeonVar_list[1] as String?
      return CounterReply(value, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      value,
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is CounterReply) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DeviceInfoRequest.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DeviceInfoReply.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CounterRequest.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CounterReply.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is DeviceInfoRequest -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is DeviceInfoReply -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is CounterRequest -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is CounterReply -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface NativeDemoApi {
  fun getDeviceInfo(request: DeviceInfoRequest): DeviceInfoReply
  fun increment(request: CounterRequest): CounterReply

  companion object {
    /** The codec used by NativeDemoApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `NativeDemoApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NativeDemoApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pigeon_demo_plugin.NativeDemoApi.getDeviceInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as DeviceInfoRequest
            val wrapped: List<Any?> = try {
              listOf(api.getDeviceInfo(requestArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pigeon_demo_plugin.NativeDemoApi.increment$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as CounterRequest
            val wrapped: List<Any?> = try {
              listOf(api.increment(requestArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
