platform :ios, '12.0'
inhibit_all_warnings!

install! 'cocoapods', disable_input_output_paths: true

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)

  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure \"flutter pub get\" is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT=(.*)/)
    return matches[1].strip if matches
  end

  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!

  flutter_install_all_ios_pods(__dir__)

  pod 'FlutterPluginRegistrant', path: File.join('Flutter', 'FlutterPluginRegistrant'), inhibit_warnings: true


  post_install do |installer|
    puts "🍎 post_install 开始执行"

    # 1. 查找 bitcode_strip 工具路径
    bitcode_strip_path = `xcrun --find bitcode_strip`.chomp
    puts "bitcode_strip_path = #{bitcode_strip_path}"

    # 2. 定义工具函数
    def strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
      framework_path = File.join(File.dirname(__FILE__), framework_relative_path)
      unless File.exist?(framework_path)
        puts "❌ Framework not found: #{framework_path}"
        return
      end
      command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
      puts "🧹 Stripping bitcode: #{command}"

      success = system(command)
      puts success ? "✅ Done." : "⚠️ Failed to strip bitcode"
    end

    # 3. 指定需要处理的 framework 二进制路径
    framework_paths = [
      "Pods/xx/xxx/xx.framework/xx"
      # 可追加更多路径
    ]

    # 4. 执行 strip 操作
    framework_paths.each do |framework_relative_path|
      strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
    end

    # 5. 修改 build 设置
    installer.pods_project.targets.each do |target|
      puts "🔧 设置构建参数: #{target.name}"

      flutter_additional_ios_build_settings(target)

      target.build_configurations.each do |config|
        puts "  ⚙️ 配置 #{config.name}"
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        config.build_settings['ENABLE_BITCODE'] = 'NO'
      end
    end

    puts "✅ post_install 执行完毕"
  end
  
end

